import BackBtn from "./BackBtn";
import "./globals.css";
import Image from "next/image";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="bg ">
          <Image src="/bg.jpg" fill={true} alt="background" />
        </div>
        <BackBtn />
        {children}
      </body>
    </html>
  );
}
