import { getServerSession } from "next-auth";
import BackBtn from "./BackBtn";
import "./globals.css";
import Image from "next/image";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        <div className="bg ">
          <Image src="/bg.jpg" fill={true} alt="background" />
        </div>
        {session ? "" : <BackBtn />}
        {children}
      </body>
    </html>
  );
}
